### ISSUE TITLE
Error with 'w2auto' and 'saveAsProject'

### ISSUE THREAD

**Issue by KeweiZhao** [gudasergey/pyFitIt#1]
Thanks for sharing this package. I ran the example and found those two issues below. I'd appreciate it if anyone could look into them.

**Issue 1: missing 'w2auto'**
```python
%matplotlib notebook
from pyfitit import *
initPyfitit()
```

    ---------------------------------------------------------------------------

    ImportError                               Traceback (most recent call last)

    <ipython-input-1-e969372f3ddb> in <module>
          1 get_ipython().run_line_magic('matplotlib', 'notebook')
    ----> 2 from pyfitit import *
          3 initPyfitit()
    

    C:\ProgramData\Anaconda3\lib\site-packages\pyfitit\__init__.py in <module>
         16 from . import adf, directMethod, factorAnalysis, fdmnes, feff, fileBrowser, geometry
         17 
    ---> 18 from . import inverseMethod, ML, molecule, optimize,  plotting, sampling, smoothLib
         19 
         20 from .project import Project, loadProject, checkProject, saveAsProject, createPartialProject
    

    C:\ProgramData\Anaconda3\lib\site-packages\pyfitit\inverseMethod.py in <module>
         11 from shutil import copyfile
         12 from .optimize import setValue
    ---> 13 from . import plotting, ML, optimize, smoothLib, fdmnes, sampling
         14 import matplotlib.pyplot as plt
         15 
    

    C:\ProgramData\Anaconda3\lib\site-packages\pyfitit\sampling.py in <module>
          3 from distutils.dir_util import copy_tree, remove_tree
          4 import copy, math, shutil, os, tempfile, json, glob
    ----> 5 from . import fdmnes, feff, adf, utils, ihs, w2auto
          6 
          7 
    

    ImportError: cannot import name 'w2auto' from 'pyfitit' (C:\ProgramData\Anaconda3\lib\site-packages\pyfitit\__init__.py)

**Issue 2: File not found in 'saveAsProject'**

```python
from pyfitit import *
saveAsProject('FeterpyProject.py')
```

    ---------------------------------------------------------------------------

    FileNotFoundError                         Traceback (most recent call last)

    <ipython-input-6-b32f5b49309f> in <module>
          1 from pyfitit import *
    ----> 2 saveAsProject('FeterpyProject.py')
    

    C:\ProgramData\Anaconda3\lib\site-packages\pyfitit\project.py in saveAsProject(fileName)
        178     fileName = utils.fixPath(fileName)
        179     notebook_path = utils.this_notebook()
    --> 180     with open(notebook_path, 'r', encoding='utf-8') as fp:
        181         notebook = nbformat.read(fp, as_version=4)
        182     project = jupytext.writes(notebook, ext='.py', fmt='py')
    

    FileNotFoundError: [Errno 2] No such file or directory: 'C:/10 Create a project.ipynb'

**Comment by gudasergey** [comment]
Thank you.
This was due to a lack of testing. 
Just run
`pip install --upgrade pyfitit`
in your python environment to update pyfitit.
